services:
  - type: web
    name: suraj-fashion-backend
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
